name: push
on:
  push:
    tags:
      - "v*"
      - "dev*"
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

defaults:
  run:
    shell: "bash"

jobs:
  draft_release:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: npm run py:install

      - run: npm run py:build

      - name: make release file(mac,linux)
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
        run: zip -r release-${{ matrix.os }}.zip ./dist

      - name: make release file(win)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          powershell Compress-Archive -Path dist -DestinationPath release-${{ matrix.os }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v') == false }}
          files: release-${{ matrix.os }}.zip
